// Generated by AlexConf: do not edit
#include <alex/LogUtil.h>
#include <alex/Alex.h>
#include <TFile.h>
#include "WriteAlexDST.hh"
namespace alex {


  WriteAlexDST::WriteAlexDST()
  {
    std::cout << "(1)" << std::endl;
   fName ="WriteAlexDST";
   fDebug ="DEBUG";
   InitLogger(fName);
   SetDebugLevel(fDebug,fName);
   std::cout << "(2)" << std::endl;
   TFile* histoFile = (TFile*) Alex::Instance().GetObject("/FAlex/FHisto/HistoFile");
   //TDirectory* adir = Alex::Instance().HistoFile().mkdir(fName.c_str());
   TDirectory* adir = histoFile->mkdir(fName.c_str());
   fDstPath = "/Users/jjgomezcadenas/Development/devnext/DATA/DST/ALEX";
   fDstName = "MagBox_Xe_10atm_00tesla.Xe136_bb0nu.alex.root";
    fNumberOfParticles_h1= new TH1F("fNumberOfParticles_h1","Number of particles in event",20,0,20);
    fNumberOfParticles_h1->SetDirectory(adir);
    fEnergyOfParticles_h1= new TH1F("fEnergyOfParticles_h1","Energy of particles in event (MeV)",30,0,3);
    fEnergyOfParticles_h1->SetDirectory(adir);
    fEnergyOfTracks_h1= new TH1F("fEnergyOfTracks_h1","Energy of tracks in event (MeV)",30,0,3);
    fEnergyOfTracks_h1->SetDirectory(adir);
    fRecEnergyOfEvent_h1= new TH1F("fRecEnergyOfEvent_h1","Reconstructed energy of event (MeV)",30,2.3,2.6);
    fRecEnergyOfEvent_h1->SetDirectory(adir);
    fTrueEnergyOfEvent_h1= new TH1F("fTrueEnergyOfEvent_h1","True energy of event (MeV)",30,2.3,2.6);
    fTrueEnergyOfEvent_h1->SetDirectory(adir);
    fTrackLength_h1= new TH1F("fTrackLength_h1","Track length of particles in event (mm)",50,0,300);
    fTrackLength_h1->SetDirectory(adir);
  }
}
