// Generated by AlexConf: do not edit
#include <alex/LogUtil.h>
#include "ReadAlexDST.hh"
namespace alex {


  ReadAlexDST::ReadAlexDST()
  {
   fName ="ReadAlexDST";
   fDebug ="DEBUG";
   InitLogger(fName);
   SetDebugLevel(fDebug,fName);
    fNumberOfParticles_h1= new TH1F("fNumberOfParticles_h1","Number of particles in event",20,0,20);
    fEnergyOfParticles_h1= new TH1F("fEnergyOfParticles_h1","Energy of particles in event (MeV)",30,0,3);
    fRecEnergyOfEvent_h1= new TH1F("fRecEnergyOfEvent_h1","Reconstructed energy of event (MeV)",30,2.3,2.6);
    fTrueEnergyOfEvent_h1= new TH1F("fTrueEnergyOfEvent_h1","True energy of event (MeV)",30,2.3,2.6);
    fTrackLength_h1= new TH1F("fTrackLength_h1","Track length of particles in event (mm)",50,0,300);
  }
}
