
#ifndef ALGOReadAlexDST_
#define ALGOReadAlexDST_
// Generated by AlexConf: do not edit
#include <string>
#include <vector>
#include <utility>
#include <memory>
#include <map>
#include <TH1F.h>
#include <TH2F.h>
#include <alex/IAlgorithm.h>
#include "PReadAlexDST.h"
namespace alex {
  class ReadAlexDST: public IAlgorithm,PReadAlexDST{
  public:
    ReadAlexDST();
    ~ReadAlexDST(){}
    bool Init() ;
    bool Execute() ;
    bool End() ;
  private:
    std::string fName ;
    std::string fDebug ;
    TH1F* fNumberOfParticles_h1;
    TH1F* fEnergyOfParticles_h1;
    TH1F* fRecEnergyOfEvent_h1;
    TH1F* fTrueEnergyOfEvent_h1;
    TH1F* fTrackLength_h1;
  };
}
#endif 
