// Generated by AlexConf: do not edit
#include <alex/Alex.h>
#include "RegisterAlgosHeader.hh"
#include "ReadAlexDST.hh"
void alex::RegisterAlgos()
{
  auto algo_ReadAlexDST=new ReadAlexDST();
  Alex::Instance().RegisterAlgorithm(algo_ReadAlexDST);
 }
