// Generated by AlexConf: do not edit
#include <alex/Alex.h>
#include "RegisterAlgosHeader.hh"
#include "WriteAlexDST.hh"
void alex::RegisterAlgos()
{
	std::cout << "call algo" << std::endl;
  auto algo_WriteAlexDST=new WriteAlexDST();
  std::cout << "register algo" << std::endl;
  Alex::Instance().RegisterAlgorithm(algo_WriteAlexDST);
  std::cout << "done" << std::endl;
 }
