
#ifndef ALGOWriteAlexDST_
#define ALGOWriteAlexDST_
// Generated by AlexConf: do not edit
#include <string>
#include <vector>
#include <utility>
#include <memory>
#include <map>
#include <TH1F.h>
#include <TH2F.h>
#include <alex/IAlgorithm.h>
#include "PWriteAlexDST.h"
namespace alex {
  class WriteAlexDST: public IAlgorithm,PWriteAlexDST{
  public:
    WriteAlexDST();
    ~WriteAlexDST(){}
    bool Init() ;
    bool Execute() ;
    bool End() ;
  private:
    std::string fName ;
    std::string fDebug ;
    std::string fDstPath;
    std::string fDstName;
    TH1F* fNumberOfParticles_h1;
    TH1F* fEnergyOfParticles_h1;
    TH1F* fEnergyOfTracks_h1;
    TH1F* fRecEnergyOfEvent_h1;
    TH1F* fTrueEnergyOfEvent_h1;
    TH1F* fTrackLength_h1;
  };
}
#endif 
